#!/usr/bin/env python3
"""Tables for the CT v85 radiological-mask study: 2x2 {v83, v85} x {unmasked, masked}.

Inputs
  --cross  cross_eval_2x2.npz written by ct_v85_cross_eval.py (four paired score
           vectors on the SAME 8000 test volumes)
  --join   ct_v80_test_join.npz (for the ES truth kinematics behind the
           pointing-information metric, and for the v80 reference scores)

The pointing-information metric and the energy binning are imported from
ct_v80_energy_topology.py, so every number is directly comparable to Table 8 of the
v80 study and to Tables A-I of the v83/v84 note.

Usage:
    python3 ct_v85_masked_tables.py --cross <npz> --join <npz> --tables <out.md>
"""

import argparse
import os
import sys

import numpy as np
from sklearn.metrics import roc_auc_score

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ct_v80_energy_topology import E_EDGES, pointing_weights

CC_REJ_POINTS = (0.945, 0.90)
_T = []


def emit(t=''):
    print(t)
    _T.append(t)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cross', required=True)
    ap.add_argument('--join', required=True)
    ap.add_argument('--tables', required=True)
    args = ap.parse_args()

    c = dict(np.load(args.cross, allow_pickle=True))
    j = dict(np.load(args.join, allow_pickle=True))

    lab = c['label'].astype(int)
    E = c['energy'].astype(np.float32)
    if not np.array_equal(lab, j['label'].astype(int)):
        raise SystemExit('FATAL: cross-eval labels differ from the v80 join')
    if not np.array_equal(E, j['particle_energy'].astype(np.float32)):
        raise SystemExit('FATAL: cross-eval energies differ from the v80 join')
    print('alignment check passed: cross-eval rows are the v80/v83 test rows, in order\n')

    es, cc = lab == 0, lab == 1
    hi = E >= 10
    theta, w, t68 = pointing_weights(j)
    wtot = float(w[es].sum())

    cells = {
        ('v80', 'unmasked'): j['p_es'].astype(np.float64),
        ('v83', 'unmasked'): c['p_es_v83_on_unmasked'].astype(np.float64),
        ('v83', 'masked'): c['p_es_v83_on_masked'].astype(np.float64),
        ('v85', 'unmasked'): c['p_es_v85_on_unmasked'].astype(np.float64),
        ('v85', 'masked'): c['p_es_v85_on_masked'].astype(np.float64),
    }
    order = [('v80', 'unmasked'), ('v83', 'unmasked'), ('v83', 'masked'),
             ('v85', 'unmasked'), ('v85', 'masked')]

    def cond_auc(p):
        out = []
        for a, b in zip(E_EDGES[:-1], E_EDGES[1:]):
            m = (E >= a) & (E < b)
            if (es & m).sum() < 10 or (cc & m).sum() < 10:
                out.append(np.nan)
            else:
                out.append(roc_auc_score(lab[m], 1 - p[m]))
        return np.array(out)

    adc = c['total_adc_unmasked']
    adcm = c['total_adc_masked']
    emit('<!-- generated by channel_tagging/ana/ct_v85_masked_tables.py -->')
    emit()
    emit(f'Mask effect on the test volumes: median total ADC '
         f'{np.median(adc):.0f} -> {np.median(adcm):.0f} '
         f'(ratio {np.median(adcm / np.maximum(adc, 1)):.4f}); '
         f'{np.mean(adcm < adc - 1e-3):.3f} of volumes lose charge; '
         f'the mask never adds charge ({np.mean(adcm <= adc + 1e-3):.3f}).')
    emit()

    # ---------------------------------------------------------------- Table J
    emit('### Table J - the 2x2: model x test images')
    emit()
    emit('All five columns are the SAME 8000 test volumes (cats 598, 600-620) in the '
         'same order; only the pixels and the model change. Thresholds are set per '
         'column to the stated CC rejection.')
    emit()
    emit('| model | test images | marginal AUC | cond. AUC range | ES eff (all) @0.945 | '
         'ES eff E>10 @0.945 | info kept @0.945 | ES eff E>10 @0.90 | info kept @0.90 |')
    emit('|---|---|---|---|---|---|---|---|---|')
    summary = {}
    for key in order:
        p = cells[key]
        ca = cond_auc(p)
        row = [f'{roc_auc_score(lab, 1 - p):.4f}',
               f'{np.nanmin(ca):.3f}-{np.nanmax(ca):.3f}']
        vals = {}
        for tgt in CC_REJ_POINTS:
            thr = float(np.quantile(p[cc], tgt))
            k = p > thr
            vals[tgt] = dict(thr=thr, eff_all=float(k[es].mean()),
                             eff_hi=float(k[es & hi].mean()),
                             rej=float(1 - k[cc].mean()),
                             info=float(w[es & k].sum()) / wtot, keep=k)
        summary[key] = {'auc': roc_auc_score(lab, 1 - p), 'cond': ca}
        summary[key].update(vals)
        emit(f'| {key[0]} | {key[1]} | ' + ' | '.join(row) +
             f' | {vals[0.945]["eff_all"]:.3f} | {vals[0.945]["eff_hi"]:.3f} |'
             f' {vals[0.945]["info"]:.3f} | {vals[0.90]["eff_hi"]:.3f} |'
             f' {vals[0.90]["info"]:.3f} |')
    emit()

    # ---------------------------------------------------------------- Table K
    emit('### Table K - conditional AUC per energy bin, 2x2')
    emit()
    emit('| E [MeV] | N(ES) | N(CC) | ' + ' | '.join(f'{m} on {i}' for m, i in order) + ' |')
    emit('|---' * (3 + len(order)) + '|')
    for n_, (a, b) in enumerate(zip(E_EDGES[:-1], E_EDGES[1:])):
        m = (E >= a) & (E < b)
        vals = [f'{summary[k]["cond"][n_]:.3f}' if np.isfinite(summary[k]['cond'][n_]) else '-'
                for k in order]
        emit(f'| {a}-{b} | {int((es & m).sum())} | {int((cc & m).sum())} | ' +
             ' | '.join(vals) + ' |')
    emit('| **all (marginal)** | 4000 | 4000 | ' +
         ' | '.join(f'**{summary[k]["auc"]:.3f}**' for k in order) + ' |')
    emit()

    # ---------------------------------------------------------------- Table L
    emit('### Table L - the two questions the 2x2 was built to answer')
    emit()
    emit('Paired differences on the same events. sigma for efficiencies is the '
         'McNemar-style sqrt(n01+n10)/N; sigma for information kept is a 2000-sample '
         'bootstrap over ES volumes.')
    emit()
    emit('| question | comparison | ES eff E>10 @0.945 | diff | sigma | info kept @0.945 | '
         'diff | sigma |')
    emit('|---|---|---|---|---|---|---|---|')
    rng = np.random.RandomState(7)
    idx_es = np.where(es)[0]
    w_es = w[idx_es]

    def boot(kA, kB, tgt):
        a = summary[kA][tgt]['keep'][idx_es]
        b = summary[kB][tgt]['keep'][idx_es]
        d = []
        for _ in range(2000):
            r = rng.randint(0, len(idx_es), len(idx_es))
            tot = w_es[r].sum()
            d.append(((w_es[r] * b[r]).sum() - (w_es[r] * a[r]).sum()) / tot)
        return float(np.mean(d)), float(np.std(d))

    def row(q, kA, kB):
        tgt = 0.945
        a = summary[kA][tgt]['keep'][es & hi]
        b = summary[kB][tgt]['keep'][es & hi]
        n01 = int((b & ~a).sum()); n10 = int((a & ~b).sum()); N = len(a)
        de = (n01 - n10) / N
        se = np.sqrt(n01 + n10) / N
        di, si = boot(kA, kB, tgt)
        emit(f'| {q} | {kA[0]} on {kA[1]} -> {kB[0]} on {kB[1]} | '
             f'{a.mean():.3f} -> {b.mean():.3f} | {de:+.3f} | {se:.3f} | '
             f'{summary[kA][tgt]["info"]:.3f} -> {summary[kB][tgt]["info"]:.3f} | '
             f'{di:+.3f} | {si:.3f} |')

    row('Does the mask help when trained on it?', ('v83', 'unmasked'), ('v85', 'masked'))
    row('Mask at test time only (train/test mismatch)', ('v83', 'unmasked'), ('v83', 'masked'))
    row('Unmasked at test time only (mismatch, other way)', ('v85', 'masked'), ('v85', 'unmasked'))
    row('Same images, masked: which training wins?', ('v83', 'masked'), ('v85', 'masked'))
    row('Same images, unmasked: which training wins?', ('v83', 'unmasked'), ('v85', 'unmasked'))
    emit()

    # ---------------------------------------------------------------- Table M
    emit('### Table M - calibration slide (median P(ES) per energy bin), 2x2')
    emit()
    emit('| E [MeV] | ' + ' | '.join(f'{m}/{i} ES | {m}/{i} CC' for m, i in order) + ' |')
    emit('|---' * (1 + 2 * len(order)) + '|')
    med = {k: {'es': [], 'cc': []} for k in order}
    for a, b in zip(E_EDGES[:-1], E_EDGES[1:]):
        m = (E >= a) & (E < b)
        vv = []
        for k in order:
            p = cells[k]
            e_ = np.median(p[es & m]) if (es & m).sum() else np.nan
            c_ = np.median(p[cc & m]) if (cc & m).sum() else np.nan
            med[k]['es'].append(e_); med[k]['cc'].append(c_)
            vv += [f'{e_:.3f}', f'{c_:.3f}']
        emit(f'| {a}-{b} | ' + ' | '.join(vv) + ' |')
    emit()
    emit('| model / images | ES slide 0-3 -> >25 | CC slide 0-3 -> >25 |')
    emit('|---|---|---|')
    for k in order:
        emit(f'| {k[0]} on {k[1]} | {med[k]["es"][-1]-med[k]["es"][0]:+.3f} | '
             f'{med[k]["cc"][-1]-med[k]["cc"][0]:+.3f} |')
    emit()

    with open(args.tables, 'w') as f:
        f.write('\n'.join(_T) + '\n')
    print(f'\nTables written to {args.tables}')


if __name__ == '__main__':
    main()
