#!/usr/bin/env python3
"""Compare CT v80 / v83 / v84 on the v80 test set, in the metrics of Table 8.

v83 and v84 are trained by `models/train_ct_volume_v83.py`, which consumes the
`RandomState(seed)` stream exactly as `train_ct_volume_v80.py` does, so the three
models are evaluated on the *same 8000 volumes in the same order*.  The script
asserts this (labels and reconstructed energies must match the v80 join
bit-for-bit) and refuses to run otherwise - so a silent mis-association is
impossible.

The pointing-information metric and the energy binning are imported from
`ct_v80_energy_topology.py` (not reimplemented), so the numbers here are directly
comparable to Table 8 of docs/CT_v80_energy_topology_study.md.

Usage:
    python3 ct_v83_v84_compare.py --join <ct_v80_test_join.npz> \
        --v83 <v83 model dir> --v84 <v84 model dir> \
        --figdir docs/figures/ct_v83_v84 --tables <out.md>
"""

import argparse
import json
import os
import sys

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ct_v80_energy_topology import (E_EDGES, pointing_weights, C_ES, C_CC, C_3,
                                    C_4, INK, INK2, GRID, SURFACE, style, newfig, save)

PRIOR_CC_PER_ES = 9.7      # natural ES:CC ratio of volumes in the test cats
CC_REJ_POINTS = (0.945, 0.90)

_TABLES = []


def emit(text=''):
    print(text)
    _TABLES.append(text)


def ebin_masks(E):
    out = []
    for a, b in zip(E_EDGES[:-1], E_EDGES[1:]):
        out.append(((a, b), (E >= a) & (E < b)))
    return out


def load_model_scores(model_dir):
    """Return (p_es, label, energy, total_adc, cat, results_dict) for a v83/v84 dir."""
    z = np.load(os.path.join(model_dir, 'test_predictions.npz'), allow_pickle=True)
    res = json.load(open(os.path.join(model_dir, 'results.json')))
    return dict(p_es=z['predictions'][:, 0].astype(np.float64),
                label=z['true_labels'].astype(int),
                energy=z['energies'].astype(np.float32),
                total_adc=z['total_adc'].astype(np.float32) if 'total_adc' in z else None,
                cat=z['cat'] if 'cat' in z else None,
                results=res)


def threshold_for_cc_rejection(p, cc, target_rej):
    """Global threshold thr with mean(p[cc] > thr) = 1 - target_rej."""
    return float(np.quantile(p[cc], target_rej))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--join', required=True, help='ct_v80_test_join.npz')
    ap.add_argument('--v83', required=True, help='v83 model dir')
    ap.add_argument('--v84', required=True, help='v84 model dir')
    ap.add_argument('--figdir', required=True)
    ap.add_argument('--tables', required=True)
    args = ap.parse_args()
    os.makedirs(args.figdir, exist_ok=True)

    j = dict(np.load(args.join, allow_pickle=True))
    E = j['particle_energy']
    lab = j['label'].astype(int)
    es, cc = lab == 0, lab == 1
    hi = E >= 10

    # pointing weights: a property of the SAMPLE (ES truth kinematics), identical
    # for all three models because the test events are identical
    theta, w_point, t68 = pointing_weights(j)
    wtot = float(w_point[es].sum())

    models = {'CT v80': dict(p_es=j['p_es'].astype(np.float64), label=lab, energy=E)}
    for name, d in (('CT v83', args.v83), ('CT v84', args.v84)):
        m = load_model_scores(d)
        # --- the identity check -------------------------------------------------
        if len(m['label']) != len(lab) or not (m['label'] == lab).all():
            raise SystemExit(f'FATAL: {name} labels differ from the v80 test set')
        if not (m['energy'] == j['particle_energy'].astype(np.float32)).all():
            n = int((m['energy'] != j['particle_energy'].astype(np.float32)).sum())
            raise SystemExit(f'FATAL: {name} energies differ from the v80 test set '
                             f'in {n}/{len(lab)} rows - the test samples are not the same')
        m['dir'] = d
        models[name] = m
    print('Identity check passed: v80, v83 and v84 were evaluated on the same '
          '8000 volumes in the same order.\n')

    names = list(models)
    emit('<!-- generated by channel_tagging/ana/ct_v83_v84_compare.py -->')
    emit()

    # ---------------------------------------------------------------- Table A
    emit('### Table A - marginal performance on the balanced test set (4000 ES + 4000 CC, cats 597-621)')
    emit()
    emit('| model | epochs | best val acc | test accuracy | marginal AUC |')
    emit('|---|---|---|---|---|')
    for n in names:
        m = models[n]
        auc = roc_auc_score(lab, 1 - m['p_es'])
        acc = float(((m['p_es'] < 0.5).astype(int) == lab).mean())
        if 'results' in m:
            ep = m['results']['epochs_trained']
            hist = os.path.join(m['dir'], 'training_history.csv')
            bv = ''
            if os.path.exists(hist):
                rows = [l.split(',') for l in open(hist).read().strip().split('\n')]
                k = rows[0].index('val_accuracy')
                bv = f'{max(float(r[k]) for r in rows[1:]):.4f}'
        else:
            ep, bv = 18, '0.7768'
        emit(f'| {n} | {ep} | {bv} | {acc:.4f} | {auc:.4f} |')
    emit()

    # ---------------------------------------------------------------- Table B
    emit('### Table B - conditional AUC in bins of reconstructed main-cluster energy')
    emit()
    emit('(0.5 = no separation. A pure energy classifier would give 0.5 in every row.)')
    emit()
    emit('| E [MeV] | N(ES) | N(CC) | ' + ' | '.join(names) + ' |')
    emit('|---' * (3 + len(names)) + '|')
    cond = {n: [] for n in names}
    for (a, b), m_ in ebin_masks(E):
        nes, ncc = int((es & m_).sum()), int((cc & m_).sum())
        cells = []
        for n in names:
            if nes < 10 or ncc < 10:
                cells.append('-'); cond[n].append(np.nan); continue
            v = roc_auc_score(lab[m_], 1 - models[n]['p_es'][m_])
            cells.append(f'{v:.3f}'); cond[n].append(v)
        emit(f'| {a}-{b} | {nes} | {ncc} | ' + ' | '.join(cells) + ' |')
    cells = [f'**{roc_auc_score(lab, 1 - models[n]["p_es"]):.3f}**' for n in names]
    emit(f'| **all (marginal)** | 4000 | 4000 | ' + ' | '.join(cells) + ' |')
    emit()
    for n in names:
        c = np.array(cond[n], float)
        emit(f'- {n}: conditional AUC range {np.nanmin(c):.3f}-{np.nanmax(c):.3f} '
             f'(mean {np.nanmean(c):.3f})')
    emit()

    # ---------------------------------------------------------------- Table C/D
    thr = {}
    keep = {}
    for target in CC_REJ_POINTS:
        for n in names:
            t = threshold_for_cc_rejection(models[n]['p_es'], cc, target)
            thr[(n, target)] = t
            keep[(n, target)] = models[n]['p_es'] > t

    emit('### Table C - global thresholds at matched CC rejection')
    emit()
    emit('| model | thr @ CC rej 0.945 | achieved CC rej | thr @ CC rej 0.90 | achieved CC rej |')
    emit('|---|---|---|---|---|')
    for n in names:
        r1 = 1 - keep[(n, 0.945)][cc].mean()
        r2 = 1 - keep[(n, 0.90)][cc].mean()
        emit(f'| {n} | {thr[(n, 0.945)]:.4f} | {r1:.4f} | {thr[(n, 0.90)]:.4f} | {r2:.4f} |')
    emit()

    for target in CC_REJ_POINTS:
        emit(f'### Table D{"1" if target == 0.945 else "2"} - ES efficiency per energy bin '
             f'at global CC rejection {target}')
        emit()
        emit('| E [MeV] | N(ES) | rel. pointing info/event | ' +
             ' | '.join(names) + ' |')
        emit('|---' * (3 + len(names)) + '|')
        ref = None
        for (a, b), m_ in ebin_masks(E):
            sel = es & m_
            n_es = int(sel.sum())
            t = t68.get((a, b), np.nan)
            info = 1.0 / t ** 2 if np.isfinite(t) else np.nan
            if ref is None and np.isfinite(info):
                ref = info
            cells = [f'{keep[(n, target)][sel].mean():.3f}' if n_es else '-' for n in names]
            emit(f'| {a}-{b} | {n_es} | {info/ref:.1f}x | ' + ' | '.join(cells) + ' |')
        emit()

    # ---------------------------------------------------------------- Table E
    emit('### Table E - working points, in the metric of Table 8 of the v80 study')
    emit()
    emit('| model | operating point | ES eff (all) | CC rej (all) | ES eff (E>10) | '
         'CC rej (E>10) | ES pointing information kept |')
    emit('|---|---|---|---|---|---|---|')
    summary = {}
    for n in names:
        for target in CC_REJ_POINTS:
            k = keep[(n, target)]
            wk = float(w_point[es & k].sum()) / wtot
            row = (float(k[es].mean()), float(1 - k[cc].mean()),
                   float(k[es & hi].mean()), float(1 - k[cc & hi].mean()), wk)
            summary[(n, target)] = row
            emit(f'| {n} | global CC rej {target} (thr {thr[(n, target)]:.3f}) | '
                 f'{row[0]:.3f} | {row[1]:.3f} | {row[2]:.3f} | {row[3]:.3f} | {row[4]:.3f} |')
    emit()
    emit('("ES pointing information kept" = fraction of sum(1/theta68(E)^2) over ES volumes '
         'that survives the selection, theta68 being the 68th percentile of the true '
         'electron-neutrino opening angle in that energy bin - exactly the last column '
         'of Table 8.)')
    emit()

    # ---------------------------------------------------------------- Table F
    emit(f'### Table F - the same selections at the natural 1:{PRIOR_CC_PER_ES} ES:CC prior')
    emit()
    emit('Efficiency and rejection are prior-independent; what the prior changes is the '
         'composition of the selected sample. For every selected ES volume the selection '
         f'admits {PRIOR_CC_PER_ES} x (1 - CC rej) / ES eff CC volumes.')
    emit()
    emit('| model | operating point | ES purity (all) | CC per ES (all) | '
         'ES purity (E>10) | CC per ES (E>10) |')
    emit('|---|---|---|---|---|---|')
    for n in names:
        for target in CC_REJ_POINTS:
            e_all, r_all, e_hi, r_hi, _ = summary[(n, target)]
            def pur(e, r):
                b = PRIOR_CC_PER_ES * (1 - r)
                return (e / (e + b) if (e + b) > 0 else np.nan,
                        b / e if e > 0 else np.inf)
            p1, c1 = pur(e_all, r_all)
            p2, c2 = pur(e_hi, r_hi)
            emit(f'| {n} | global CC rej {target} | {p1:.3f} | {c1:.2f} | '
                 f'{p2:.3f} | {c2:.2f} |')
    emit()
    emit('(The E>10 MeV rows use the ES:CC ratio of the balanced test set restricted to '
         'E>10 MeV rescaled by the same global 1:9.7 prior, i.e. they answer "of the '
         'selected E>10 MeV volumes, what fraction is ES" only under the assumption that '
         'the prior is energy-independent; the true CC spectrum is harder than the ES one, '
         'so these are optimistic. The prior-independent numbers are in Table E.)')
    emit()

    # ---------------------------------------------------------------- Table G
    emit('### Table G - the calibration slide: median score per energy bin')
    emit()
    emit('| E [MeV] | ' + ' | '.join(f'{n} ES | {n} CC' for n in names) + ' |')
    emit('|---' * (1 + 2 * len(names)) + '|')
    med = {n: {'es': [], 'cc': []} for n in names}
    for (a, b), m_ in ebin_masks(E):
        cells = []
        for n in names:
            p = models[n]['p_es']
            me = np.median(p[es & m_]) if (es & m_).sum() else np.nan
            mc = np.median(p[cc & m_]) if (cc & m_).sum() else np.nan
            med[n]['es'].append(me); med[n]['cc'].append(mc)
            cells += [f'{me:.3f}', f'{mc:.3f}']
        emit(f'| {a}-{b} | ' + ' | '.join(cells) + ' |')
    emit()
    emit('| model | median P(ES) for ES: 0-3 -> >25 | slide | for CC: 0-3 -> >25 | slide |')
    emit('|---|---|---|---|---|')
    for n in names:
        e0, e1 = med[n]['es'][0], med[n]['es'][-1]
        c0, c1 = med[n]['cc'][0], med[n]['cc'][-1]
        emit(f'| {n} | {e0:.3f} -> {e1:.3f} | {e1-e0:+.3f} | {c0:.3f} -> {c1:.3f} | {c1-c0:+.3f} |')
    emit()

    # ---------------------------------------------------------------- Table H
    # CONTROL: the reweighting was done in particle_energy, so testing flatness in
    # particle_energy is partly circular.  Repeat in deciles of total volume ADC,
    # which was not used to build the weights (cf. Table 3b of the v80 study).
    adc = j['total_adc']
    qs = np.quantile(adc, np.linspace(0, 1, 11)); qs[-1] += 1
    emit('### Table H - control: conditional AUC and median score in deciles of total volume ADC')
    emit()
    emit('The weights were built in `particle_energy`, so Tables B and G partly condition on '
         'the variable used to construct them. Total ADC was not used to build the weights.')
    emit()
    emit('| total ADC range | N(ES) | N(CC) | ' +
         ' | '.join(f'{n} AUC' for n in names) + ' | ' +
         ' | '.join(f'{n} med ES/CC' for n in names) + ' |')
    emit('|---' * (3 + 2 * len(names)) + '|')
    slide = {n: [] for n in names}
    for lo, up in zip(qs[:-1], qs[1:]):
        m_ = (adc >= lo) & (adc < up)
        nes, ncc = int((es & m_).sum()), int((cc & m_).sum())
        aucs, meds = [], []
        for n in names:
            p_ = models[n]['p_es']
            aucs.append(f'{roc_auc_score(lab[m_], 1 - p_[m_]):.3f}'
                        if nes >= 10 and ncc >= 10 else '-')
            me = np.median(p_[es & m_]) if nes else np.nan
            mc = np.median(p_[cc & m_]) if ncc else np.nan
            meds.append(f'{me:.3f}/{mc:.3f}')
            slide[n].append((me, mc))
        emit(f'| {lo:.0f}-{up:.0f} | {nes} | {ncc} | ' + ' | '.join(aucs) + ' | ' +
             ' | '.join(meds) + ' |')
    emit()
    emit('| model | median P(ES), ES: first -> last ADC decile | slide | CC: first -> last | slide |')
    emit('|---|---|---|---|---|')
    for n in names:
        (e0, c0), (e1, c1) = slide[n][0], slide[n][-1]
        emit(f'| {n} | {e0:.3f} -> {e1:.3f} | {e1-e0:+.3f} | {c0:.3f} -> {c1:.3f} | {c1-c0:+.3f} |')
    emit()

    # ---------------------------------------------------------------- Table I
    emit('### Table I - is v84 really better than v83? (paired, same events)')
    emit()
    emit('McNemar-style paired comparison of the two selections at matched CC rejection: '
         'n01 = ES volumes v84 keeps and v83 does not, n10 = the reverse. '
         'sigma(difference) = sqrt(n01 + n10) / N.')
    emit()
    emit('| quantity | operating point | v83 | v84 | difference | sigma | n01 | n10 |')
    emit('|---|---|---|---|---|---|---|---|')
    for label, sel in (('ES eff (all)', es), ('ES eff (E>10)', es & hi)):
        for target in CC_REJ_POINTS:
            a = keep[('CT v83', target)][sel]
            b = keep[('CT v84', target)][sel]
            n01 = int((b & ~a).sum()); n10 = int((a & ~b).sum()); N = len(a)
            d = (n01 - n10) / N
            sig = np.sqrt(n01 + n10) / N
            emit(f'| {label} | CC rej {target} | {a.mean():.3f} | {b.mean():.3f} | '
                 f'{d:+.3f} | {sig:.3f} | {n01} | {n10} |')
    # bootstrap on the information-kept difference (resample ES volumes)
    rng = np.random.RandomState(1)
    idx_es = np.where(es)[0]
    for target in CC_REJ_POINTS:
        w_es = w_point[idx_es]
        k83 = keep[('CT v83', target)][idx_es]
        k84 = keep[('CT v84', target)][idx_es]
        k80 = keep[('CT v80', target)][idx_es]
        boot = []
        for _ in range(2000):
            r = rng.randint(0, len(idx_es), len(idx_es))
            tot = w_es[r].sum()
            boot.append(((w_es[r] * k84[r]).sum() - (w_es[r] * k83[r]).sum()) / tot)
        b8 = []
        for _ in range(2000):
            r = rng.randint(0, len(idx_es), len(idx_es))
            tot = w_es[r].sum()
            b8.append(((w_es[r] * k84[r]).sum() - (w_es[r] * k80[r]).sum()) / tot)
        emit(f'| information kept | CC rej {target} | '
             f'{(w_es*k83).sum()/w_es.sum():.3f} | {(w_es*k84).sum()/w_es.sum():.3f} | '
             f'{np.mean(boot):+.3f} | {np.std(boot):.3f} (bootstrap) | - | - |')
        emit(f'| information kept vs v80 | CC rej {target} | '
             f'{(w_es*k80).sum()/w_es.sum():.3f} (v80) | '
             f'{(w_es*k84).sum()/w_es.sum():.3f} (v84) | '
             f'{np.mean(b8):+.3f} | {np.std(b8):.3f} (bootstrap) | - | - |')
    emit()

    # ---------------------------------------------------------------- figure
    colors = {'CT v80': C_CC, 'CT v83': C_ES, 'CT v84': C_3}
    marks = {'CT v80': 'o', 'CT v83': 's', 'CT v84': '^'}
    xc, xerr = [], []
    for a, b in zip(E_EDGES[:-1], E_EDGES[1:]):
        b_ = 35.0 if b > 90 else b
        xc.append(0.5 * (a + b_)); xerr.append(0.5 * (b_ - a))
    fig, ax = newfig(figsize=(6.6, 4.4))
    for n in names:
        eff, err = [], []
        for (a, b), m_ in ebin_masks(E):
            sel = es & m_
            k = keep[(n, 0.945)][sel]
            p_ = float(k.mean()); nn = max(len(k), 1)
            eff.append(p_); err.append(np.sqrt(max(p_ * (1 - p_), 1e-9) / nn))
        ax.errorbar(xc, eff, yerr=err, xerr=xerr, color=colors[n], lw=2, marker=marks[n],
                    ms=6, capsize=0, ls='-', label=n)
    ax.set_ylim(0, 1.02)
    style(ax, 'reconstructed main-cluster energy [MeV]', 'ES efficiency',
          'ES efficiency vs energy at matched CC rejection 0.945')
    ax.legend(frameon=False, fontsize=9, labelcolor=INK2, loc='upper right',
              bbox_to_anchor=(1.0, 0.88))
    ax.annotate('v80: an anti-selection on pointing power\n(efficiency falls by a factor 300)',
                xy=(12.5, 0.06), xytext=(14.0, 0.62), fontsize=8, color=C_CC,
                ha='left', va='center',
                arrowprops=dict(arrowstyle='-', color=C_CC, lw=0.8, alpha=0.6))
    ax.annotate('v83 / v84: roughly flat above 5 MeV\n- the score no longer encodes energy',
                xy=(20.0, 0.215), xytext=(14.0, 0.40), fontsize=8, color=C_ES,
                ha='left', va='center',
                arrowprops=dict(arrowstyle='-', color=C_ES, lw=0.8, alpha=0.6))
    ax.text(0.99, -0.155, 'last bin is E > 25 MeV, drawn as 25-35',
            transform=ax.transAxes, fontsize=7, color=INK2, ha='right')
    save(fig, args.figdir, 'fig_es_efficiency_vs_energy_ccrej0945.png')

    with open(args.tables, 'w') as f:
        f.write('\n'.join(_TABLES) + '\n')
    print(f'\nTables written to {args.tables}')
    json.dump({f'{n}|{t}': summary[(n, t)] for n in names for t in CC_REJ_POINTS},
              open(os.path.splitext(args.tables)[0] + '_summary.json', 'w'), indent=2)


if __name__ == '__main__':
    main()
