universe                = vanilla
executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/scripts/wrapper_ct_v80.sh
arguments               = -j /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/json/volume_v80_aux.json

request_cpus            = 4
request_memory          = 100GB
request_gpus            = 1
request_disk            = 15GB

+JobFlavour             = "nextweek"
requirements            = (OpSysAndVer =?= "AlmaLinux9")

initialdir              = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing
getenv                  = True

log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v80_aux_$(Cluster).log
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v80_aux_$(Cluster).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v80_aux_$(Cluster).err

notification            = Error
queue 1
