executable            = wrapper_ct_v62_three_plane.sh
arguments             = -j /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/channel_tagging/json/v62_three_plane_200k.json
output                = /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/channel_tagging/logs/ct_v62.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/channel_tagging/logs/ct_v62.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/channel_tagging/logs/ct_v62.$(ClusterId).log
request_GPUs          = 1
request_memory        = 250GB
+JobFlavour           = "tomorrow"
queue 1
