# CT v79 training variant
# Same as submit_volume_v79.sub but with reduced disk request (4GB).
universe                = vanilla
executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/scripts/wrapper_ct_simple.sh
arguments               = -j /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/json/volume_v79.json

request_cpus            = 4
request_memory          = 120GB
request_gpus            = 1
request_disk            = 4GB

+JobFlavour             = "nextweek"
requirements            = (OpSysAndVer =?= "AlmaLinux9")

initialdir              = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing
getenv                  = True

log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v79_disk4_$(Cluster).log
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v79_disk4_$(Cluster).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v79_disk4_$(Cluster).err

notification            = Error

queue 1
