universe                = vanilla
executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/scripts/wrapper_ct_v80.sh
arguments               = -j /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/json/three_plane_volumes_v82.json -s channel_tagging/models/train_ct_three_plane_volumes_v82.py

# three planes (U+V+X); images held sparse, so the job is small
request_cpus            = 4
request_memory          = 16GB
request_gpus            = 1
request_disk            = 15GB

+JobFlavour             = "nextweek"
requirements            = (OpSysAndVer =?= "AlmaLinux9") && (GPUs_GlobalMemoryMb >= 20000)

initialdir              = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing
getenv                  = True

log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v82_$(Cluster).log
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v82_$(Cluster).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/channel_tagging/condor/logs/CT_v82_$(Cluster).err

notification            = Error
queue 1
