# ED v61: three-plane ED retrain on sn-burst-samples ES clusters (cat split as CT v80)
universe                = vanilla
executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/electron_direction/scripts/wrapper_ed_v61_burstcats.sh
arguments               = -j /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/electron_direction/json/three_plane_v61_burstcats_es.json

request_cpus            = 4
request_memory          = 40GB
request_gpus            = 1
request_disk            = 5GB

+JobFlavour             = "tomorrow"
requirements            = (OpSysAndVer =?= "AlmaLinux9")

initialdir              = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing
getenv                  = True

log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/electron_direction/condor/logs/ED_v61_burstcats_es_$(Cluster).log
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/electron_direction/condor/logs/ED_v61_burstcats_es_$(Cluster).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor-ml-for-pointing/electron_direction/condor/logs/ED_v61_burstcats_es_$(Cluster).err

notification            = Error
queue 1
