# HTCondor submission for ED v52 (hyperopt like v14)
executable = /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/electron_direction/scripts/condor/wrapper_ed_v52_hyperopt.sh
arguments = -j /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/electron_direction/json/v52.json

output = /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/electron_direction/condor/logs/three_plane_v52_hyperopt_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/electron_direction/condor/logs/three_plane_v52_hyperopt_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/ml-pointing-tools/electron_direction/condor/logs/three_plane_v52_hyperopt_$(ClusterId).log

request_cpus = 4
request_memory = 40GB
request_disk = 10GB
request_gpus = 1

+JobFlavour = "tomorrow"
queue 1
